version: "3.8"
services:
  quiz-n-chill:
    image: laosteven/quiz-n-chill:latest
    container_name: quiz-n-chill
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
    volumes:
      - ./games:/app/games:ro
